trigger:
- master

variables:
- group: powershell-gallery

stages:
- stage: Test
  jobs:
  - job: Unit tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - powershell: .\test.ps1
      workingDirectory: $(build.sourcesDirectory)
      displayName: Running unit tests

    - task: PublishTestResults@2
      displayName: Public tests results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: output.xml
        failTaskOnFailedTests: true
      
- stage: Deploy
  jobs:
  - job: Publish to PSGallery
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - powershell: .\publish.ps1
      env: {
        NUGET_API_KEY: $(nuget-api-key)
      }