name: continuous-integration

on:
  push:
    branches: master

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Run unit tests with Pester
        run: pwsh -File ./test.ps1
