name: continuous-integration

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Run tests
    steps:
    
    - name: Run unit tests
      run: powershell .\test.ps1
      
    - name: Upload coverage
      run: powershell .\upload-coverage.ps1
   
   deploy:
    name: Publish
    needs: test
    steps:
    
      - name: Publish to PSGallery
        run: powershell publish.ps1
