name: continuous deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubunutu-latest
    steps:
      - run: ./build.sh Publish
    env:
      NUKE_NUGETAPIKEY: ${{ secrets.PSGALLERY_APIKEY }}
