name: deployment

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v4

      - name: Run continuous deployment
        shell: pwsh
        run: ./build/Start-Deployment.ps1 -Verbose
        env:
          PSGALLERY_APIKEY: ${{ secrets.PSGALLERY_APIKEY }}
