name: continuous integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v3

      - name: Lint sources
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Recurse -Severity Warning ./StepSemVer/
      
      - name: Run unit tests
        shell: pwsh
        run: ./build/test.ps1
